### ISSUE TITLE
CALCULATOR-75

### ISSUE THREAD

**Issue by EvGeN1s** [tss-calculator/tools#2]
`apllication/service/platform.go:100`
Мб стоит логировать как ошибку ситуацию, когда мы пытаемся мержить несуществующую ветку?

Ещё вопрос про dry-run и force. Сейчас, насколько я понимаю, если флаг не указан, то команда pyshContext не будет пушить изменения, даже в случае, если все ОК. Мб оставить термин dry-run для команды pysh-context? 
Мб я чето путаю и оно на самом деле норм работает, просто подозрительный вопрос

**Comment by veresnikov** [comment]
1) там оптимизон, чтоб не пытаться мержить ветку в себя же. Это только на уровне конфига проверки. Как это работает:
Контекст наследуется от базового, соответсвенно там поидее не будет ситуации когда бранч не существует, он есть всегда, но я перестраховался. И там же проверка, а не пытаюсь ли я смержить ветку репозиторий в одну и ту же ветку
2) обсудили в чатике, пока оставим так
